(use-modules (guix git)
	     (guix packages)
	     ((guix licenses) #:prefix license:)
	     (guix build-system trivial)
	     (gnu packages)
	     (gnu packages dlang)
	     (gnu packages ruby)
	     (gnu packages groff))

(package
  (name "trash-d")
  (version "18")
  (source (git-checkout (url (dirname (current-filename)))))
  (native-inputs (list dub ronn-ng ruby-rake))
  (build-system trivial-build-system)
  (arguments `(#:builder (system "rake build:release:strip")))
  (synopsis "Near drop-in replacement for rm that uses the trash bin")
  (description "A near drop-in replacement for GNU rm that uses the FreeDesktop trash bin.")
  (home-page "https://github.com/rushsteve1/trash-d")
  (license license:expat))
