name: D

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-latest

    - name: Test
      run: rake test:coverage

    - name: Build
      run: rake build:release:strip

    - name: Man Page with Ronn
      run: |
        sudo gem install ronn-ng
        rake manpage

    - name: Distro Packages
      run: |
        sudo gem install fpm
        rake package

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: "trash-d"
        path: |
          build/trash
          build/trash.man

    - name: Upload Coverage Logs
      uses: actions/upload-artifact@v2
      with:
        name: "coverage-logs"
        path: "build/coverage/*.lst"

    - name: Upload Packages
      uses: actions/upload-artifact@v2
      with:
        name: "built-packages"
        path: |
          build/*.deb
          build/*.rpm

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    #- uses: dlang-community/setup-dlang@v1
      #with:
        #compiler: ldc-latest
    - name: Install dependencies
      run: |
        brew update
        brew install ldc dub
    - name: Test
      run: rake test:coverage
    - name: Build
      run: rake build:release:strip
