name: D

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v2
    - uses: dlang-community/setup-dlang@v2
      with:
        compiler: ldc-latest

    - name: Test
      run: just coverage

    - name: Build
      run: just release

    - name: Man Page with Scdoc
      run: |
        sudo apt install scdoc
        just manpage

    - name: Distro Packages
      run: |
        sudo gem install fpm
        rake package

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "trash-d"
        path: |
          build/trash
          build/trash.1
  
    - name: Upload Coverage Logs
      uses: actions/upload-artifact@v4
      with:
        name: "coverage-logs"
        path: "build/coverage/*.lst"

    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: "built-packages"
        path: |
          build/*.deb
          build/*.rpm
